name: 'Configure Google Cloud CLI'
description: 'Sets up Google Cloud CLI with the provided service account key and project ID.'

runs:
  using: 'docker'
  image: 'hashicorp/setup-terraform:latest'

inputs:
  service_account_key:
    description: 'The service account key JSON file.'
    required: true
  project_id:
    description: 'The Google Cloud project ID.'
    required: true

outputs:
  none

branding:
  icon: 'cloud'
  color: 'blue'

permissions:
  contents: 'read'
  packages: 'write'
  actions: 'write'
